/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the frontend refresh button / dev smoke tests.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/rate-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Rate Diff */
        get: operations["get_dashboard_rate_diff_api_dashboard_rate_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/pending-reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Pending Reconciliation */
        get: operations["get_dashboard_pending_reconciliation_api_dashboard_pending_reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/courier-billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Courier Billing */
        get: operations["get_dashboard_courier_billing_api_dashboard_courier_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bills */
        get: operations["list_bills_api_bills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/couriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Couriers */
        get: operations["list_couriers_api_couriers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discrepancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Discrepancies */
        get: operations["get_discrepancies_api_discrepancies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discrepancies/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reconciliation */
        get: operations["get_reconciliation_api_discrepancies_reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/claimable-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claimable Rate */
        get: operations["get_claimable_rate_api_disputes_claimable_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dispute Lines */
        get: operations["get_dispute_lines_api_disputes_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dispute Invoices */
        get: operations["get_dispute_invoices_api_disputes_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings-opportunity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Savings Opportunity */
        get: operations["get_savings_opportunity_api_savings_opportunity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cod": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cod */
        get: operations["get_cod_api_cod_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cod/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cod Pending */
        get: operations["get_cod_pending_api_cod_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cod/intelligence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cod Intelligence */
        get: operations["get_cod_intelligence_api_cod_intelligence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Zones */
        get: operations["get_zones_api_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weight */
        get: operations["get_weight_api_weight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_api_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend-recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend Recovery */
        get: operations["get_trend_recovery_api_trend_recovery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sla-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sla Performance */
        get: operations["get_sla_performance_api_sla_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Catalog */
        get: operations["export_catalog_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export File */
        get: operations["export_file_api_export__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/lines/export/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Dispute Lines
         * @description CSV/XLSX of the CURRENT filtered dispute-line set — the artifact ops sends
         *     to carriers. Reuses the export renderer; builds the set inline if the page
         *     hasn't warmed it yet.
         */
        get: operations["export_dispute_lines_api_disputes_lines_export__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/invoices/export/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Dispute Invoices
         * @description CSV/XLSX invoice SUMMARY (one row per carrier invoice) for the current filter —
         *     the artifact a carrier contact acts on. Line-item export stays separate.
         */
        get: operations["export_dispute_invoices_api_disputes_invoices_export__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_profile_patch"];
        trace?: never;
    };
    "/api/profile/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_profile_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/_meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Metadata
         * @description Per-page/per-panel provenance map used to render Live/Sample badges.
         */
        get: operations["source_metadata_api__meta_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp Status */
        get: operations["mcp_status_api__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_status/schedulers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scheduler Status
         * @description ADMIN-ONLY, additive, read-only. Background warm-cache scheduler telemetry
         *     (cache age / next refresh) from the EXISTING warm timestamps — changes no
         *     scheduler behavior and touches no existing response.
         */
        get: operations["scheduler_status_api__status_schedulers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bill */
        Bill: {
            /** Id */
            id: number;
            /** Awb */
            awb: string;
            /** Courier */
            courier: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight */
            weight: number;
            /** Zone */
            zone: string;
            /** Amount */
            amount: number;
            /** Cod */
            cod: number;
            status: components["schemas"]["BillStatus"];
        };
        /**
         * BillStatus
         * @enum {string}
         */
        BillStatus: "delivered" | "in_transit" | "pending" | "rto" | "discrepancy";
        /**
         * Capability
         * @description A dashboard capability whose feasibility is decided LIVE from the MCP tool
         *     schemas (not a hardcoded list). `available` flips as the server exposes new
         *     tools / params — e.g. courier-wise reconciliation unblocked when
         *     reconciliation_summary(group_by=courier) appeared.
         */
        Capability: {
            /** Domain */
            domain: string;
            /** Capability */
            capability: string;
            /** Needs */
            needs: string;
            /** Resolved By */
            resolved_by?: string | null;
            /** Available */
            available: boolean;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ClaimableRateResponse
         * @description Claimable rate difference = Σ rate_diff over reconciliation_disputes rows that
         *     are (a) material (rate_diff ≥ threshold) AND (b) actually priced (applied rate > 0).
         *     Rows without an applied rate can't be claimed (the whole invoice looks like an
         *     overcharge) and small diffs are noise — both are surfaced, not hidden.
         */
        ClaimableRateResponse: {
            /**
             * Claimable Amount
             * @default 0
             */
            claimable_amount: number;
            /**
             * Excluded No Applied Rate
             * @default 0
             */
            excluded_no_applied_rate: number;
            /**
             * Excluded Below Threshold
             * @default 0
             */
            excluded_below_threshold: number;
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Threshold
             * @default 50
             */
            threshold: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
            /**
             * Computing
             * @default false
             */
            computing: boolean;
            /**
             * Recalculating
             * @default false
             */
            recalculating: boolean;
            /**
             * Maturing
             * @default false
             */
            maturing: boolean;
        };
        /**
         * CodCourier
         * @description Per-courier COD value (order_analytics group_by=courier).
         */
        CodCourier: {
            /** Courier */
            courier: string;
            /** Orders */
            orders: number;
            /** Cod Value */
            cod_value: number;
        };
        /**
         * CodDimensionRow
         * @description One warehouse/seller row (order_analytics group_by=warehouse|seller). COD
         *     intensity = the row's own cod_value / order_value (single row, single tool).
         */
        CodDimensionRow: {
            /** Group */
            group: string;
            /** Orders */
            orders: number;
            /** Order Value */
            order_value: number;
            /** Cod Value */
            cod_value: number;
            /** Cod Intensity Pct */
            cod_intensity_pct: number;
        };
        /**
         * CodIntelligenceResponse
         * @description Additive COD-intelligence layer. All KPIs are live MCP fields or ratios of
         *     live fields from a SINGLE tool (never cross-tool, never fabricated).
         */
        CodIntelligenceResponse: {
            /**
             * Kpis
             * @default []
             */
            kpis: components["schemas"]["Kpi"][];
            /**
             * Payment Split
             * @default []
             */
            payment_split: components["schemas"]["CodPaymentSplit"][];
            /**
             * Unit Economics
             * @default []
             */
            unit_economics: components["schemas"]["CodPaymentEconomics"][];
            /**
             * Warehouse Cod
             * @default []
             */
            warehouse_cod: components["schemas"]["CodDimensionRow"][];
            /**
             * Seller Cod
             * @default []
             */
            seller_cod: components["schemas"]["CodDimensionRow"][];
            /**
             * Unavailable
             * @default []
             */
            unavailable: components["schemas"]["CodUnavailableMetric"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /**
         * CodPaymentEconomics
         * @description Per-payment-type unit economics. Cost fields are the shipping_cost_summary
         *     (group_by=payment_type) live values; avg_order_value is order_analytics
         *     order_value / orders for the SAME payment type (never blended).
         */
        CodPaymentEconomics: {
            /** Payment Type */
            payment_type: string;
            /** Orders */
            orders: number;
            /** Avg Order Value */
            avg_order_value: number;
            /** Avg Shipping Cost */
            avg_shipping_cost: number;
            /** Fwd Cost */
            fwd_cost: number;
            /** Rto Cost */
            rto_cost: number;
            /** Total Cost */
            total_cost: number;
        };
        /**
         * CodPaymentSplit
         * @description COD vs Prepaid order/value split (order_analytics group_by=payment_type).
         */
        CodPaymentSplit: {
            /** Payment Type */
            payment_type: string;
            /** Orders */
            orders: number;
            /** Order Value */
            order_value: number;
        };
        /**
         * CodPendingCourier
         * @description Per-courier COD aging (cod_remittance_aging group_by=courier), joined with
         *     order_analytics for the COD amount.
         */
        CodPendingCourier: {
            /** Courier */
            courier: string;
            /** Cod Shipments */
            cod_shipments: number;
            /** Cod Amount */
            cod_amount?: number | null;
            /** Remitted */
            remitted: number;
            /** Pending */
            pending: number;
            /** Status */
            status: string;
        };
        /** CodPendingResponse */
        CodPendingResponse: {
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["CodPendingCourier"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** CodResponse */
        CodResponse: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Reconciliation */
            reconciliation: components["schemas"]["CodCourier"][];
            /** Weekly */
            weekly: components["schemas"]["CodWeekly"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /**
         * CodUnavailableMetric
         * @description An intelligence metric that CANNOT be derived from the MCP, with the exact
         *     missing capability. Surfaced verbatim so the UI can show 'Not available from
         *     MCP' honestly instead of fabricating a value.
         */
        CodUnavailableMetric: {
            /** Metric */
            metric: string;
            /** Reason */
            reason: string;
        };
        /**
         * CodWeekly
         * @description One weekly window. Both are GLOBAL (no per-courier split exists).
         */
        CodWeekly: {
            /** Week */
            week: string;
            /** Collected */
            collected: number;
            /** Remitted */
            remitted: number;
        };
        /** Courier */
        Courier: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Shipments */
            shipments: number;
            /** Avg Cost */
            avg_cost: number;
            /** On Time Pct */
            on_time_pct: number;
            /** Total Billing */
            total_billing: number;
            /** Rto Pct */
            rto_pct: number;
            /** Cod Value */
            cod_value: number;
            /** Freight */
            freight: number;
            /** Rto */
            rto: number;
            /** Remitted */
            remitted?: number | null;
            /** Status */
            status?: string | null;
        };
        /** CourierBillingResponse */
        CourierBillingResponse: {
            /** Rows */
            rows: components["schemas"]["CourierBillingRow"][];
            /** Sample Size */
            sample_size: number;
            /** Total Matched */
            total_matched: number;
            /**
             * Is Full
             * @default false
             */
            is_full: boolean;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /**
         * CourierBillingRow
         * @description Per-courier FORWARD cost broken into real rate_summary components
         *     (fuel/other are always 0 → omitted). base_freight/gst/cod_charges are SAMPLED
         *     (sample-scale ₹). rto_actual is the REAL population RTO cost from
         *     shipping_cost_summary — kept separate (rate_summary.rto is a quoted rate
         *     carried on ~99% of orders, not actual returns), rendered in its own chart.
         */
        CourierBillingRow: {
            /** Courier */
            courier: string;
            /** Base Freight */
            base_freight: number;
            /** Gst */
            gst: number;
            /** Cod Charges */
            cod_charges: number;
            /** Total */
            total: number;
            /** Rto Actual */
            rto_actual: number;
        };
        /**
         * CourierRate
         * @description Per-courier RTO% or NDR% (count ÷ that courier's orders). 0.0 if none.
         */
        CourierRate: {
            /** Courier */
            courier: string;
            /** Rate Pct */
            rate_pct: number;
            /** Count */
            count: number;
            /** Orders */
            orders: number;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Distribution */
            distribution: components["schemas"]["DistributionSlice"][];
            /** State Cost */
            state_cost: components["schemas"]["StateCostRow"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** DiscrepancyResponse */
        DiscrepancyResponse: {
            rate_diff: components["schemas"]["RateDiff"];
            /** Rto */
            rto: components["schemas"]["CourierRate"][];
            /** Ndr */
            ndr: components["schemas"]["CourierRate"][];
            /** Ndr Orders */
            ndr_orders: number;
            /** Ndr Avg Attempts */
            ndr_avg_attempts: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Recon Date Field
             * @default reconciliation_at
             */
            recon_date_field: string;
            /**
             * Order Date Field
             * @default order_date
             */
            order_date_field: string;
        };
        /**
         * DisputeInvoiceGroup
         * @description One carrier invoice = a bundle of dispute lines. Totals are summed from the
         *     SAME enumerated priced lines as the flat view, so Σ(rate_diff_total) equals the
         *     claimable KPI exactly (never from reconciliation_summary, which is capped and
         *     counts non-disputed lines too).
         */
        DisputeInvoiceGroup: {
            /** Invoice No */
            invoice_no: string;
            /** Courier */
            courier: string;
            /** Line Count */
            line_count: number;
            /** Rate Diff Total */
            rate_diff_total: number;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
        };
        /** DisputeInvoicesResponse */
        DisputeInvoicesResponse: {
            /**
             * Invoices
             * @default []
             */
            invoices: components["schemas"]["DisputeInvoiceGroup"][];
            /**
             * Total Matched
             * @default 0
             */
            total_matched: number;
            /**
             * Claimable Amount
             * @default 0
             */
            claimable_amount: number;
            /**
             * Excluded No Applied Rate
             * @default 0
             */
            excluded_no_applied_rate: number;
            /**
             * Couriers
             * @default []
             */
            couriers: string[];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
            /**
             * Min Diff
             * @default 50
             */
            min_diff: number;
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Computing
             * @default false
             */
            computing: boolean;
            /**
             * Recalculating
             * @default false
             */
            recalculating: boolean;
        };
        /** DisputeLine */
        DisputeLine: {
            /** Awb */
            awb: string;
            /** Invoice No */
            invoice_no?: string | null;
            /** Courier */
            courier: string;
            /** Courier Slug */
            courier_slug: string;
            /** Order Date */
            order_date?: string | null;
            /**
             * Is Rto
             * @default false
             */
            is_rto: boolean;
            /** Applied Weight Kg */
            applied_weight_kg: number;
            /** Invoiced Weight Kg */
            invoiced_weight_kg: number;
            /** Weight Diff Kg */
            weight_diff_kg: number;
            /** Applied Rate */
            applied_rate: number;
            /** Invoiced Rate */
            invoiced_rate: number;
            /** Rate Diff */
            rate_diff: number;
            /** Status */
            status: string;
        };
        /** DisputeLinesResponse */
        DisputeLinesResponse: {
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["DisputeLine"][];
            /**
             * Total Matched
             * @default 0
             */
            total_matched: number;
            /**
             * Claimable Amount
             * @default 0
             */
            claimable_amount: number;
            /**
             * Excluded No Applied Rate
             * @default 0
             */
            excluded_no_applied_rate: number;
            /**
             * Couriers
             * @default []
             */
            couriers: string[];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /**
             * Min Diff
             * @default 50
             */
            min_diff: number;
            /**
             * Sort By
             * @default rate_diff
             */
            sort_by: string;
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Computing
             * @default false
             */
            computing: boolean;
            /**
             * Recalculating
             * @default false
             */
            recalculating: boolean;
        };
        /** DistributionSlice */
        DistributionSlice: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** EndpointStatus */
        EndpointStatus: {
            /** Endpoint */
            endpoint: string;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /** Mcp Tools */
            mcp_tools: string[];
            /** Load Ms */
            load_ms: number;
            /** Notes */
            notes: string;
        };
        /** ExportCatalog */
        ExportCatalog: {
            /** Datasets */
            datasets: components["schemas"]["ExportDataset"][];
            /** Formats */
            formats: string[];
        };
        /** ExportDataset */
        ExportDataset: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Rows */
            rows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Kpi */
        Kpi: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /**
             * Format
             * @enum {string}
             */
            format: "currency" | "number" | "percent";
            /** Delta */
            delta: number;
            /**
             * Delta Tone
             * @enum {string}
             */
            delta_tone: "positive" | "negative" | "neutral";
            /**
             * Has Delta
             * @default false
             */
            has_delta: boolean;
            /** Subtitle */
            subtitle?: string | null;
            /**
             * Unavailable
             * @default false
             */
            unavailable: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Page[Bill] */
        Page_Bill_: {
            /** Items */
            items: components["schemas"]["Bill"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            /**
             * Source
             * @default live
             * @enum {string}
             */
            source: "live" | "sample" | "unavailable";
        };
        /**
         * PendingReconciliationResponse
         * @description 'Pending Reconciliation' KPI — for the reconciliation lines still unreconciled
         *     (recon status 'Disputed') in the selected window, from
         *     reconciliation_summary(group_by=status):
         *       • amount = the ₹ rate difference on those lines (invoiced − applied) — the money
         *         pending reconciliation. This is the displayed KPI value.
         *       • count  = how many lines are pending (kept as additive context).
         *     Reconciliation-book basis, so date_field = reconciliation_at. On MCP failure the
         *     response is source='unavailable' with zeros — never fixture/sample values.
         */
        PendingReconciliationResponse: {
            /**
             * Amount
             * @default 0
             */
            amount: number;
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
        };
        /**
         * Preferences
         * @description System info only — hardcoded throughout the app (₹ INR, IST dates, kg).
         */
        Preferences: {
            /** Currency */
            currency: string;
            /** Timezone */
            timezone: string;
            /** Weight Unit */
            weight_unit: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
        };
        /**
         * RateDiff
         * @description Aggregate weight-reconciliation figures (reconciliation LINES, not AWBs).
         */
        RateDiff: {
            /** Reconciliation Lines */
            reconciliation_lines: number;
            /** Weight Overcharged */
            weight_overcharged: number;
            /** Weight Diff Kg */
            weight_diff_kg: number;
            /** Fwd Rate Diff */
            fwd_rate_diff: number;
            /** Reconciled */
            reconciled: number;
            /** Disputed */
            disputed: number;
            /**
             * Has Recon
             * @default true
             */
            has_recon: boolean;
        };
        /**
         * RateDiffKpi
         * @description Isolated 'Rate Diff to Investigate' KPI (weight_reconciliation is slow, so
         *     it is fetched separately from the main dashboard).
         */
        RateDiffKpi: {
            kpi: components["schemas"]["Kpi"];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
        };
        /** RateDispute */
        RateDispute: {
            /** Awb */
            awb: string;
            /** Courier */
            courier: string;
            /** Applied Rate */
            applied_rate: number;
            /** Invoiced Rate */
            invoiced_rate: number;
            /** Rate Diff */
            rate_diff: number;
        };
        /** ReconciledCourier */
        ReconciledCourier: {
            /** Courier */
            courier: string;
            /** Reconciled Lines */
            reconciled_lines: number;
            /** Reconciled Amount */
            reconciled_amount: number;
        };
        /** ReconciliationResponse */
        ReconciliationResponse: {
            /**
             * Weight Disputes
             * @default []
             */
            weight_disputes: components["schemas"]["WeightDispute"][];
            /**
             * Weight Total
             * @default 0
             */
            weight_total: number;
            /**
             * Rate Disputes
             * @default []
             */
            rate_disputes: components["schemas"]["RateDispute"][];
            /**
             * Rate Total
             * @default 0
             */
            rate_total: number;
            /**
             * Reconciled
             * @default []
             */
            reconciled: components["schemas"]["ReconciledCourier"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** RecoveryPoint */
        RecoveryPoint: {
            /** Month */
            month: string;
            /** Identified */
            identified: number;
            /** Cumulative */
            cumulative: number;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /**
             * Gap
             * @default false
             */
            gap: boolean;
        };
        /** RecoveryResponse */
        RecoveryResponse: {
            /** Points */
            points: components["schemas"]["RecoveryPoint"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
            /**
             * Computing
             * @default false
             */
            computing: boolean;
            /**
             * Recalculating
             * @default false
             */
            recalculating: boolean;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "employee" | "operations" | "finance" | "viewer";
        /** SavingRow */
        SavingRow: {
            /** Awb */
            awb: string;
            /** Courier Used */
            courier_used: string;
            /** Applied */
            applied: number;
            /** Cheapest Courier */
            cheapest_courier: string;
            /** Cheapest Rate */
            cheapest_rate: number;
            /** Saving */
            saving: number;
            /** Cheapest Rto Pct */
            cheapest_rto_pct: number;
        };
        /** SavingsResponse */
        SavingsResponse: {
            /** Rows */
            rows: components["schemas"]["SavingRow"][];
            /** Sampled */
            sampled: number;
            /** Skipped */
            skipped: number;
            /** Total Saving */
            total_saving: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Note
             * @default Theoretical maximum — ignores SLA, capacity and routing rules.
             */
            note: string;
        };
        /**
         * SchedulerStatus
         * @description Read-only telemetry for one background warm-cache scheduler (admin-only view).
         *     Timestamps are monotonic → age/next are relative seconds, not wall-clock.
         */
        SchedulerStatus: {
            /** Name */
            name: string;
            /** Cadence Seconds */
            cadence_seconds: number;
            /** Running */
            running: boolean;
            /** Warm */
            warm: boolean;
            /** Cache Age Seconds */
            cache_age_seconds?: number | null;
            /** Next Refresh Seconds */
            next_refresh_seconds?: number | null;
        };
        /** SchedulersResponse */
        SchedulersResponse: {
            /**
             * Schedulers
             * @default []
             */
            schedulers: components["schemas"]["SchedulerStatus"][];
        };
        /** SettingsResponse */
        SettingsResponse: {
            preferences: components["schemas"]["Preferences"];
        };
        /** SlaResponse */
        SlaResponse: {
            /**
             * Delivered
             * @default 0
             */
            delivered: number;
            /**
             * On Time
             * @default 0
             */
            on_time: number;
            /**
             * Late
             * @default 0
             */
            late: number;
            /**
             * On Time Pct
             * @default 0
             */
            on_time_pct: number;
            /**
             * Avg Delay Days
             * @default 0
             */
            avg_delay_days: number;
            /**
             * Overdue In Transit
             * @default 0
             */
            overdue_in_transit: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** StateCostRow */
        StateCostRow: {
            /** State */
            state: string;
            /** Total Cost */
            total_cost: number;
        };
        /** StateRow */
        StateRow: {
            /** State */
            state: string;
            /** Orders */
            orders: number;
            /** Total Cost */
            total_cost: number;
            /** Avg Cost */
            avg_cost: number;
            /** Fwd Cost */
            fwd_cost: number;
            /** Rto Cost */
            rto_cost: number;
            /** Delivery Rate Pct */
            delivery_rate_pct: number;
            /** Rto Rate Pct */
            rto_rate_pct: number;
            /** Ndr Rate Pct */
            ndr_rate_pct: number;
            /** Avg Delivery Days */
            avg_delivery_days: number;
            /**
             * Joined
             * @default true
             */
            joined: boolean;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Mcp Connected */
            mcp_connected: boolean;
            /** Mcp Url */
            mcp_url: string;
            /** Tool Count */
            tool_count: number;
            /** Token Present */
            token_present: boolean;
            /** Endpoints */
            endpoints: components["schemas"]["EndpointStatus"][];
            /**
             * Capabilities
             * @default []
             */
            capabilities: components["schemas"]["Capability"][];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserPublic"];
        };
        /** TrendDay */
        TrendDay: {
            /** Day */
            day: string;
            /** Orders */
            orders: number;
            /** Order Value */
            order_value: number;
        };
        /** TrendResponse */
        TrendResponse: {
            /** Daily */
            daily: components["schemas"]["TrendDay"][];
            /** Couriers */
            couriers: string[];
            /** By Month */
            by_month: {
                [key: string]: string | number;
            }[];
            /**
             * Partial Months
             * @default []
             */
            partial_months: string[];
            /**
             * Window
             * @default
             */
            window: string;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            role: components["schemas"]["Role"];
        };
        /**
         * UserPublic
         * @description The safe, client-facing representation of a user (no password).
         */
        UserPublic: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["Role"];
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightBucket */
        WeightBucket: {
            /** Bucket */
            bucket: string;
            /** Count */
            count: number;
        };
        /** WeightDispute */
        WeightDispute: {
            /** Awb */
            awb: string;
            /** Courier */
            courier: string;
            /** Expected Weight Kg */
            expected_weight_kg: number;
            /** Billed Weight Kg */
            billed_weight_kg: number;
            /** Weight Diff Kg */
            weight_diff_kg: number;
            /** Status */
            status: string;
        };
        /** WeightPoint */
        WeightPoint: {
            /** Actual */
            actual: number;
            /** Charged */
            charged: number;
            /** Courier */
            courier: string;
        };
        /** WeightResponse */
        WeightResponse: {
            /** Scatter */
            scatter: components["schemas"]["WeightPoint"][];
            /** Histogram */
            histogram: components["schemas"]["WeightBucket"][];
            summary: components["schemas"]["WeightSummary"];
            /**
             * Sample Size
             * @default 0
             */
            sample_size: number;
            /**
             * Total Matched
             * @default 0
             */
            total_matched: number;
            /**
             * Is Full
             * @default false
             */
            is_full: boolean;
            /**
             * Sampled Rows
             * @default 0
             */
            sampled_rows: number;
            /**
             * Missing Weight Count
             * @default 0
             */
            missing_weight_count: number;
            /**
             * Missing Weight Pct
             * @default 0
             */
            missing_weight_pct: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Recon Date Field
             * @default reconciliation_at
             */
            recon_date_field: string;
            /**
             * Sample Date Field
             * @default order_date
             */
            sample_date_field: string;
        };
        /** WeightSummary */
        WeightSummary: {
            /** Reconciliation Lines */
            reconciliation_lines: number;
            /** Weight Overcharged */
            weight_overcharged: number;
            /** Weight Diff Kg */
            weight_diff_kg: number;
            /** Fwd Rate Diff */
            fwd_rate_diff: number;
            /** Reconciled */
            reconciled: number;
            /** Disputed */
            disputed: number;
            /**
             * Has Recon
             * @default true
             */
            has_recon: boolean;
        };
        /** ZonesResponse */
        ZonesResponse: {
            /** States */
            states: components["schemas"]["StateRow"][];
            /**
             * Unjoined
             * @default []
             */
            unjoined: string[];
            /**
             * Unmapped
             * @default []
             */
            unmapped: string[];
            /**
             * Unmapped Count
             * @default 0
             */
            unmapped_count: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock" | "unavailable";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_rate_diff_api_dashboard_rate_diff_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateDiffKpi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_pending_reconciliation_api_dashboard_pending_reconciliation_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingReconciliationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_courier_billing_api_dashboard_courier_billing_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourierBillingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bills_api_bills_get: {
        parameters: {
            query?: {
                /** @description Match AWB, courier, or zone */
                search?: string | null;
                status?: components["schemas"]["BillStatus"] | null;
                /** @description field:dir e.g. amount:desc */
                sort?: string | null;
                page?: number;
                page_size?: number;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Bill_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_couriers_api_couriers_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Courier"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discrepancies_api_discrepancies_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscrepancyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reconciliation_api_discrepancies_reconciliation_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claimable_rate_api_disputes_claimable_rate_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimableRateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dispute_lines_api_disputes_lines_get: {
        parameters: {
            query?: {
                min_diff?: number;
                sort_by?: string;
                courier_slug?: string | null;
                invoice_no?: string | null;
                page?: number;
                page_size?: number;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeLinesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dispute_invoices_api_disputes_invoices_get: {
        parameters: {
            query?: {
                min_diff?: number;
                courier_slug?: string | null;
                invoice_no?: string | null;
                page?: number;
                page_size?: number;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeInvoicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_savings_opportunity_api_savings_opportunity_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cod_api_cod_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cod_pending_api_cod_pending_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodPendingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cod_intelligence_api_cod_intelligence_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodIntelligenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zones_api_zones_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weight_api_weight_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_api_trend_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_recovery_api_trend_recovery_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sla_performance_api_sla_performance_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    export_catalog_api_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportCatalog"];
                };
            };
        };
    };
    export_file_api_export__fmt__get: {
        parameters: {
            query?: {
                dataset?: string;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path: {
                fmt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_dispute_lines_api_disputes_lines_export__fmt__get: {
        parameters: {
            query?: {
                min_diff?: number;
                sort_by?: string;
                courier_slug?: string | null;
                invoice_no?: string | null;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path: {
                fmt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_dispute_invoices_api_disputes_invoices_export__fmt__get: {
        parameters: {
            query?: {
                min_diff?: number;
                courier_slug?: string | null;
                invoice_no?: string | null;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path: {
                fmt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_profile_api_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_profile_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_metadata_api__meta_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
    mcp_status_api__status_get: {
        parameters: {
            query?: {
                /** @description Also probe the slow endpoints (savings-opportunity, trend-recovery). */
                include_slow?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_status_api__status_schedulers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulersResponse"];
                };
            };
        };
    };
}
