/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the frontend refresh button / dev smoke tests.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/rate-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Rate Diff */
        get: operations["get_dashboard_rate_diff_api_dashboard_rate_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/courier-billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Courier Billing */
        get: operations["get_dashboard_courier_billing_api_dashboard_courier_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bills */
        get: operations["list_bills_api_bills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/couriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Couriers */
        get: operations["list_couriers_api_couriers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discrepancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Discrepancies */
        get: operations["get_discrepancies_api_discrepancies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings-opportunity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Savings Opportunity */
        get: operations["get_savings_opportunity_api_savings_opportunity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cod": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cod */
        get: operations["get_cod_api_cod_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Zones */
        get: operations["get_zones_api_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weight */
        get: operations["get_weight_api_weight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_api_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend-recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend Recovery */
        get: operations["get_trend_recovery_api_trend_recovery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Catalog */
        get: operations["export_catalog_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export File */
        get: operations["export_file_api_export__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_profile_patch"];
        trace?: never;
    };
    "/api/profile/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_profile_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/_meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Metadata
         * @description Per-page/per-panel provenance map used to render Live/Sample badges.
         */
        get: operations["source_metadata_api__meta_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp Status */
        get: operations["mcp_status_api__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bill */
        Bill: {
            /** Id */
            id: number;
            /** Awb */
            awb: string;
            /** Courier */
            courier: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight */
            weight: number;
            /** Zone */
            zone: string;
            /** Amount */
            amount: number;
            /** Cod */
            cod: number;
            status: components["schemas"]["BillStatus"];
        };
        /**
         * BillStatus
         * @enum {string}
         */
        BillStatus: "delivered" | "in_transit" | "pending" | "rto" | "discrepancy";
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * CodCourier
         * @description Per-courier COD value (order_analytics group_by=courier).
         */
        CodCourier: {
            /** Courier */
            courier: string;
            /** Orders */
            orders: number;
            /** Cod Value */
            cod_value: number;
        };
        /** CodResponse */
        CodResponse: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Reconciliation */
            reconciliation: components["schemas"]["CodCourier"][];
            /** Weekly */
            weekly: components["schemas"]["CodWeekly"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /**
         * CodWeekly
         * @description One weekly window. Both are GLOBAL (no per-courier split exists).
         */
        CodWeekly: {
            /** Week */
            week: string;
            /** Collected */
            collected: number;
            /** Remitted */
            remitted: number;
        };
        /** Courier */
        Courier: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Shipments */
            shipments: number;
            /** Avg Cost */
            avg_cost: number;
            /** On Time Pct */
            on_time_pct: number;
            /** Total Billing */
            total_billing: number;
            /** Rto Pct */
            rto_pct: number;
            /** Cod Value */
            cod_value: number;
            /** Freight */
            freight: number;
            /** Rto */
            rto: number;
            /** Remitted */
            remitted?: number | null;
        };
        /** CourierBillingResponse */
        CourierBillingResponse: {
            /** Rows */
            rows: components["schemas"]["CourierBillingRow"][];
            /** Sample Size */
            sample_size: number;
            /** Total Matched */
            total_matched: number;
            /**
             * Is Full
             * @default false
             */
            is_full: boolean;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /**
         * CourierBillingRow
         * @description Per-courier FORWARD cost broken into real rate_summary components
         *     (fuel/other are always 0 → omitted). base_freight/gst/cod_charges are SAMPLED
         *     (sample-scale ₹). rto_actual is the REAL population RTO cost from
         *     shipping_cost_summary — kept separate (rate_summary.rto is a quoted rate
         *     carried on ~99% of orders, not actual returns), rendered in its own chart.
         */
        CourierBillingRow: {
            /** Courier */
            courier: string;
            /** Base Freight */
            base_freight: number;
            /** Gst */
            gst: number;
            /** Cod Charges */
            cod_charges: number;
            /** Total */
            total: number;
            /** Rto Actual */
            rto_actual: number;
        };
        /**
         * CourierRate
         * @description Per-courier RTO% or NDR% (count ÷ that courier's orders). 0.0 if none.
         */
        CourierRate: {
            /** Courier */
            courier: string;
            /** Rate Pct */
            rate_pct: number;
            /** Count */
            count: number;
            /** Orders */
            orders: number;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Distribution */
            distribution: components["schemas"]["DistributionSlice"][];
            /** State Cost */
            state_cost: components["schemas"]["StateCostRow"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** DiscrepancyResponse */
        DiscrepancyResponse: {
            rate_diff: components["schemas"]["RateDiff"];
            /** Rto */
            rto: components["schemas"]["CourierRate"][];
            /** Ndr */
            ndr: components["schemas"]["CourierRate"][];
            /** Ndr Orders */
            ndr_orders: number;
            /** Ndr Avg Attempts */
            ndr_avg_attempts: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Recon Date Field
             * @default reconciliation_at
             */
            recon_date_field: string;
            /**
             * Order Date Field
             * @default order_date
             */
            order_date_field: string;
        };
        /** DistributionSlice */
        DistributionSlice: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** EndpointStatus */
        EndpointStatus: {
            /** Endpoint */
            endpoint: string;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "mock";
            /** Mcp Tools */
            mcp_tools: string[];
            /** Load Ms */
            load_ms: number;
            /** Notes */
            notes: string;
        };
        /** ExportCatalog */
        ExportCatalog: {
            /** Datasets */
            datasets: components["schemas"]["ExportDataset"][];
            /** Formats */
            formats: string[];
        };
        /** ExportDataset */
        ExportDataset: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Rows */
            rows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Kpi */
        Kpi: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /**
             * Format
             * @enum {string}
             */
            format: "currency" | "number" | "percent";
            /** Delta */
            delta: number;
            /**
             * Delta Tone
             * @enum {string}
             */
            delta_tone: "positive" | "negative" | "neutral";
            /**
             * Has Delta
             * @default false
             */
            has_delta: boolean;
            /** Subtitle */
            subtitle?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Page[Bill] */
        Page_Bill_: {
            /** Items */
            items: components["schemas"]["Bill"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * Preferences
         * @description System info only — hardcoded throughout the app (₹ INR, IST dates, kg).
         */
        Preferences: {
            /** Currency */
            currency: string;
            /** Timezone */
            timezone: string;
            /** Weight Unit */
            weight_unit: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
        };
        /**
         * RateDiff
         * @description Aggregate weight-reconciliation figures (reconciliation LINES, not AWBs).
         */
        RateDiff: {
            /** Reconciliation Lines */
            reconciliation_lines: number;
            /** Weight Overcharged */
            weight_overcharged: number;
            /** Weight Diff Kg */
            weight_diff_kg: number;
            /** Fwd Rate Diff */
            fwd_rate_diff: number;
            /** Reconciled */
            reconciled: number;
            /** Disputed */
            disputed: number;
            /**
             * Has Recon
             * @default true
             */
            has_recon: boolean;
        };
        /**
         * RateDiffKpi
         * @description Isolated 'Rate Diff to Investigate' KPI (weight_reconciliation is slow, so
         *     it is fetched separately from the main dashboard).
         */
        RateDiffKpi: {
            kpi: components["schemas"]["Kpi"];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
        };
        /** RecoveryPoint */
        RecoveryPoint: {
            /** Month */
            month: string;
            /** Identified */
            identified: number;
            /** Cumulative */
            cumulative: number;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /**
             * Gap
             * @default false
             */
            gap: boolean;
        };
        /** RecoveryResponse */
        RecoveryResponse: {
            /** Points */
            points: components["schemas"]["RecoveryPoint"][];
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default reconciliation_at
             */
            date_field: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "employee" | "operations" | "finance" | "viewer";
        /** SavingRow */
        SavingRow: {
            /** Awb */
            awb: string;
            /** Courier Used */
            courier_used: string;
            /** Applied */
            applied: number;
            /** Cheapest Courier */
            cheapest_courier: string;
            /** Cheapest Rate */
            cheapest_rate: number;
            /** Saving */
            saving: number;
            /** Cheapest Rto Pct */
            cheapest_rto_pct: number;
        };
        /** SavingsResponse */
        SavingsResponse: {
            /** Rows */
            rows: components["schemas"]["SavingRow"][];
            /** Sampled */
            sampled: number;
            /** Skipped */
            skipped: number;
            /** Total Saving */
            total_saving: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Note
             * @default Theoretical maximum — ignores SLA, capacity and routing rules.
             */
            note: string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            preferences: components["schemas"]["Preferences"];
        };
        /** StateCostRow */
        StateCostRow: {
            /** State */
            state: string;
            /** Total Cost */
            total_cost: number;
        };
        /** StateRow */
        StateRow: {
            /** State */
            state: string;
            /** Orders */
            orders: number;
            /** Total Cost */
            total_cost: number;
            /** Avg Cost */
            avg_cost: number;
            /** Fwd Cost */
            fwd_cost: number;
            /** Rto Cost */
            rto_cost: number;
            /** Delivery Rate Pct */
            delivery_rate_pct: number;
            /** Rto Rate Pct */
            rto_rate_pct: number;
            /** Ndr Rate Pct */
            ndr_rate_pct: number;
            /** Avg Delivery Days */
            avg_delivery_days: number;
            /**
             * Joined
             * @default true
             */
            joined: boolean;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Mcp Connected */
            mcp_connected: boolean;
            /** Mcp Url */
            mcp_url: string;
            /** Tool Count */
            tool_count: number;
            /** Token Present */
            token_present: boolean;
            /** Endpoints */
            endpoints: components["schemas"]["EndpointStatus"][];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserPublic"];
        };
        /** TrendDay */
        TrendDay: {
            /** Day */
            day: string;
            /** Orders */
            orders: number;
            /** Order Value */
            order_value: number;
        };
        /** TrendResponse */
        TrendResponse: {
            /** Daily */
            daily: components["schemas"]["TrendDay"][];
            /** Couriers */
            couriers: string[];
            /** By Month */
            by_month: {
                [key: string]: string | number;
            }[];
            /**
             * Partial Months
             * @default []
             */
            partial_months: string[];
            /**
             * Window
             * @default
             */
            window: string;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            role: components["schemas"]["Role"];
        };
        /**
         * UserPublic
         * @description The safe, client-facing representation of a user (no password).
         */
        UserPublic: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["Role"];
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightBucket */
        WeightBucket: {
            /** Bucket */
            bucket: string;
            /** Count */
            count: number;
        };
        /** WeightPoint */
        WeightPoint: {
            /** Actual */
            actual: number;
            /** Charged */
            charged: number;
            /** Courier */
            courier: string;
        };
        /** WeightResponse */
        WeightResponse: {
            /** Scatter */
            scatter: components["schemas"]["WeightPoint"][];
            /** Histogram */
            histogram: components["schemas"]["WeightBucket"][];
            summary: components["schemas"]["WeightSummary"];
            /**
             * Sample Size
             * @default 0
             */
            sample_size: number;
            /**
             * Total Matched
             * @default 0
             */
            total_matched: number;
            /**
             * Is Full
             * @default false
             */
            is_full: boolean;
            /**
             * Sampled Rows
             * @default 0
             */
            sampled_rows: number;
            /**
             * Missing Weight Count
             * @default 0
             */
            missing_weight_count: number;
            /**
             * Missing Weight Pct
             * @default 0
             */
            missing_weight_pct: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Recon Date Field
             * @default reconciliation_at
             */
            recon_date_field: string;
            /**
             * Sample Date Field
             * @default order_date
             */
            sample_date_field: string;
        };
        /** WeightSummary */
        WeightSummary: {
            /** Reconciliation Lines */
            reconciliation_lines: number;
            /** Weight Overcharged */
            weight_overcharged: number;
            /** Weight Diff Kg */
            weight_diff_kg: number;
            /** Fwd Rate Diff */
            fwd_rate_diff: number;
            /** Reconciled */
            reconciled: number;
            /** Disputed */
            disputed: number;
            /**
             * Has Recon
             * @default true
             */
            has_recon: boolean;
        };
        /** ZonesResponse */
        ZonesResponse: {
            /** States */
            states: components["schemas"]["StateRow"][];
            /**
             * Unjoined
             * @default []
             */
            unjoined: string[];
            /**
             * Unmapped
             * @default []
             */
            unmapped: string[];
            /**
             * Unmapped Count
             * @default 0
             */
            unmapped_count: number;
            /**
             * Source
             * @default mock
             * @enum {string}
             */
            source: "live" | "mock";
            /**
             * Date Field
             * @default order_date
             */
            date_field: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_rate_diff_api_dashboard_rate_diff_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateDiffKpi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_courier_billing_api_dashboard_courier_billing_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourierBillingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bills_api_bills_get: {
        parameters: {
            query?: {
                /** @description Match AWB, courier, or zone */
                search?: string | null;
                status?: components["schemas"]["BillStatus"] | null;
                /** @description field:dir e.g. amount:desc */
                sort?: string | null;
                page?: number;
                page_size?: number;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Bill_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_couriers_api_couriers_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Courier"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discrepancies_api_discrepancies_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscrepancyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_savings_opportunity_api_savings_opportunity_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cod_api_cod_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zones_api_zones_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weight_api_weight_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_api_trend_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_recovery_api_trend_recovery_get: {
        parameters: {
            query?: {
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    export_catalog_api_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportCatalog"];
                };
            };
        };
    };
    export_file_api_export__fmt__get: {
        parameters: {
            query?: {
                dataset?: string;
                /** @description Start date YYYY-MM-DD */
                from?: string | null;
                /** @description End date YYYY-MM-DD */
                to?: string | null;
            };
            header?: never;
            path: {
                fmt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_profile_api_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_profile_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_metadata_api__meta_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
    mcp_status_api__status_get: {
        parameters: {
            query?: {
                /** @description Also probe the slow endpoints (savings-opportunity, trend-recovery). */
                include_slow?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
